In [1]:
from pathlib import Path
import pandas as pd

data_dir = Path("./mgat1ko_data/nav")

cm = pd.read_excel(data_dir/"capacitance.xlsx")

## Normalize current traces by the cell capacitance

In [25]:
fpaths = (data_dir/"wt-trace").glob("*.xlsx")
fnames = [f.stem for f in fpaths]

for idx,row in cm[cm['group']=='WT'].iterrows():
    if str(row.file_name) in fnames:
        print(f"File {idx}: {row.file_name} is in file list")
    else:
        print(f"File {idx}: {row.file_name} is NOT in file list")

File 0: 18o18002 is in file list
File 1: 18111002 is in file list
File 2: 18111007 is in file list
File 3: 18112001 is in file list
File 4: 18116006 is in file list
File 5: 18116011 is in file list
File 6: 18116016 is in file list
File 7: 18122004 is in file list
File 8: 18122010 is in file list
File 9: 18124001 is in file list
File 10: 18124006 is in file list
File 11: 18124011 is in file list
File 12: 18124016 is in file list
File 13: 18129001 is in file list
File 14: 18129013 is in file list
File 15: 18129018 is in file list
File 16: 18201001 is in file list
File 17: 18201009 is in file list
File 18: 18201027 is in file list
File 19: 18201031 is in file list
File 20: 18713004 is in file list
File 21: 18717001 is in file list
File 22: 18717007 is in file list

In [27]:
fpaths = (data_dir/"mgat1ko-trace").glob("*.xlsx")
fnames = [f.stem for f in fpaths]

for idx,row in cm[cm['group']=='MGAT1KO'].iterrows():
    if str(row.file_name) in fnames:
        print(f"File {idx}: {row.file_name} is in file list")
    else:
        print(f"File {idx}: {row.file_name} is NOT in file list")

File 23: 18118001 is in file list
File 24: 18118004 is in file list
File 25: 18118009 is in file list
File 26: 18118010 is in file list
File 27: 18118015 is in file list
File 28: 18119001 is in file list
File 29: 18119006 is in file list
File 30: 18123001 is in file list
File 31: 18123006 is in file list
File 32: 18123009 is in file list
File 33: 18123012 is in file list
File 34: 18126002 is in file list
File 35: 18130001 is in file list
File 36: 18130013 is in file list
File 37: 18130018 is in file list
File 38: 18131001 is in file list

In [34]:
for idx,row in cm[cm['group']=='WT'].iterrows():
    p = data_dir/"wt-trace"/(str(row.file_name)+".xlsx")
    ctrace = pd.read_excel(p)
    ctrace.iloc[:,2:] = ctrace.iloc[:,2:]/long(row.cm)

NameError: name 'long' is not defined

In [31]:
ctrace = pd.read_excel(Path("mgat1ko_data/nav/wt-trace/18o18002.xlsx"))

In [33]:
ctrace.iloc[:,2:]

,-80.00(Im),-75.00(Im),-70.00(Im),-65.00(Im),-60.00(Im),-55.00(Im),-50.00(Im),-45.00(Im),-40.00(Im),-35.00(Im),...,-35.00(ImC),-30.00(ImC),-25.00(ImC),-20.00(ImC),-15.00(ImC),-10.00(ImC),-5.00(ImC),0.00(ImC),5.00(ImC),10.00(ImC)
0,-262.451141,-262.451141,-286.865204,-268.554657,-299.072235,-329.589813,-305.175751,-360.107391,-378.417938,-378.417938,...,36.621090,-36.621090,-48.828121,12.207030,12.207030,-24.414061,48.828121,-36.621090,12.207030,-30.517576
1,-274.658173,-268.554657,-292.968719,-268.554657,-299.072235,-317.382782,-323.486298,-354.003876,-378.417938,-372.314423,...,48.828121,-67.138664,-30.517576,24.414061,6.103515,-6.103515,30.517576,0.000000,6.103515,-42.724606
2,-274.658173,-244.140610,-292.968719,-262.451141,-292.968719,-323.486298,-323.486298,-372.314423,-378.417938,-378.417938,...,6.103515,-42.724606,-30.517576,-12.207030,18.310545,-24.414061,48.828121,-6.103515,0.000000,-73.242180
3,-286.865204,-244.140610,-280.761688,-244.140610,-305.175751,-311.279266,-311.279266,-378.417938,-384.521454,-384.521454,...,6.103515,-30.517576,-18.310545,-18.310545,36.621090,18.310545,24.414061,18.310545,-6.103515,-54.931637
4,-268.554657,-250.244125,-286.865204,-238.037094,-305.175751,-311.279266,-323.486298,-372.314423,-366.210907,-390.624969,...,0.000000,0.000000,-36.621090,-24.414061,61.035152,18.310545,12.207030,42.724606,0.000000,-36.621090
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,-256.347626,-274.658173,-305.175751,-305.175751,-341.796844,-390.624969,-469.970673,-457.763641,-524.902283,-531.005798,...,-140.380844,-341.796844,-213.623032,-341.796844,-280.761688,-292.968719,-286.865204,-463.867157,-292.968719,726.318298
2996,-286.865204,-280.761688,-299.072235,-305.175751,-335.693329,-402.832001,-488.281219,-469.970673,-512.695251,-518.798767,...,-91.552727,-329.589813,-238.037094,-341.796844,-286.865204,-329.589813,-268.554657,-488.281219,-299.072235,732.421814
2997,-268.554657,-280.761688,-305.175751,-317.382782,-341.796844,-415.039032,-488.281219,-469.970673,-512.695251,-494.384735,...,-73.242180,-347.900360,-244.140610,-347.900360,-292.968719,-323.486298,-274.658173,-482.177704,-311.279266,720.214783
2998,-268.554657,-280.761688,-311.279266,-317.382782,-329.589813,-415.039032,-469.970673,-482.177704,-531.005798,-506.591766,...,-122.070305,-347.900360,-250.244125,-341.796844,-280.761688,-347.900360,-250.244125,-439.453094,-280.761688,726.318298
2999,-268.554657,-274.658173,-311.279266,-317.382782,-317.382782,-408.935516,-469.970673,-463.867157,-537.109314,-488.281219,...,-146.484360,-311.279266,-238.037094,-329.589813,-231.933578,-360.107391,-256.347626,-469.970673,-311.279266,726.318298